---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: default
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    status:
      lastOperation:
        state: Succeeded
      observedGeneration: 1