#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

repo_root="$(readlink -f $(dirname ${0})/..)"

echo "Generating ${repo_root}/dev/extension/kustomization.yaml"
mkdir -p ${repo_root}/dev/extension

cat <<EOF >${repo_root}/dev/extension/kustomization.yaml
# DO NOT EDIT THIS FILE!
# This file is auto-generated by hack/prepare-dev-extension.sh.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../example/extension.yaml

patches:
- path: ../../hack/skaffold-extension-patch.yaml
EOF
