apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}