apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coreos.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreos.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}