apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coreos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreos.labels" . | nindent 4 }}
automountServiceAccountToken: false
