apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: os-coreos
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
  - kind: OperatingSystemConfig
    type: flatcar
