name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}

  oci-images:
    name: Build OCI-Images
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@master
    with:
      name: gardener-extension-os-coreos
      version: ${{ needs.prepare.outputs.version }}
      oci-repository: extensions/os-coreos
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-platforms: linux/amd64
      target: gardener-extension-os-coreos
      ocm-labels: |
        name: cloud.gardener.cnudie/responsibles
        value:
        - type: githubUser
          username: MrBatschner
        - type: githubUser
          username: Roncossek
        - type: githubUser
          username: Vincinator

  helmcharts:
    name: Build Helmcharts
    needs:
      - prepare
      - oci-images
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@master
    with:
      name: os-coreos
      dir: charts/gardener-extension-os-coreos
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: charts/gardener/extensions
      ocm-mappings: |
        - ref: ocm-resource:gardener-extension-os-coreos.repository
          attribute: image.repository
        - ref: ocm-resource:gardener-extension-os-coreos.tag
          attribute: image.tag

  sast-lint:
    name: run gosec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: run-gosec
        run: |
          set -euo pipefail
          mkdir blobs.d
          .ci/verify |& tee blobs.d/gosec-scan-log.txt
      - uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
        with:
          ocm-resources: |
            name: sast-linting-evidence
            relation: local
            access:
              type: localBlob
              localReference: gosec-scan-log.txt
            labels:
              - name: gardener.cloud/purposes
                value:
                  - lint
                  - sast
                  - gosec
              - name: gardener.cloud/comment
                value: |
                  we use gosec (linter) for SAST scans
                  see: https://github.com/securego/gosec
                  enabled by https://github.com/gardener/gardener/pull/9959
